<script src="https://giscus.app/client.js"
        data-repo="suziyanglinyi/document"
        data-repo-id="R_kgDOMz1wWQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOMz1wWc4Cimg1"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="1"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
